//
// FhirResource.swift
//
// A enum defining the full list of Named Resources in FHIR 4.3.0
// 
// Generated:    2024-05-16
// FHIR Version: 4.3.0 [updated: 2022-05-28T12:47:40+10:00]

enum FhirResource: String, Codable {
    case account                        = "Account"
    case activityDefinition             = "ActivityDefinition"
    case administrableProductDefinition = "AdministrableProductDefinition"
    case adverseEvent                   = "AdverseEvent"
    case allergyIntolerance             = "AllergyIntolerance"
    case appointment                    = "Appointment"
    case appointmentResponse            = "AppointmentResponse"
    case auditEvent                     = "AuditEvent"
    case basic                          = "Basic"
    case biologicallyDerivedProduct     = "BiologicallyDerivedProduct"
    case bodyStructure                  = "BodyStructure"
    case capabilityStatement            = "CapabilityStatement"
    case carePlan                       = "CarePlan"
    case careTeam                       = "CareTeam"
    case catalogEntry                   = "CatalogEntry"
    case chargeItem                     = "ChargeItem"
    case chargeItemDefinition           = "ChargeItemDefinition"
    case citation                       = "Citation"
    case claim                          = "Claim"
    case claimResponse                  = "ClaimResponse"
    case clinicalImpression             = "ClinicalImpression"
    case clinicalUseDefinition          = "ClinicalUseDefinition"
    case codeSystem                     = "CodeSystem"
    case communication                  = "Communication"
    case communicationRequest           = "CommunicationRequest"
    case compartmentDefinition          = "CompartmentDefinition"
    case composition                    = "Composition"
    case conceptMap                     = "ConceptMap"
    case condition                      = "Condition"
    case consent                        = "Consent"
    case contract                       = "Contract"
    case coverage                       = "Coverage"
    case coverageEligibilityRequest     = "CoverageEligibilityRequest"
    case coverageEligibilityResponse    = "CoverageEligibilityResponse"
    case detectedIssue                  = "DetectedIssue"
    case device                         = "Device"
    case deviceDefinition               = "DeviceDefinition"
    case deviceMetric                   = "DeviceMetric"
    case deviceRequest                  = "DeviceRequest"
    case deviceUseStatement             = "DeviceUseStatement"
    case diagnosticReport               = "DiagnosticReport"
    case documentManifest               = "DocumentManifest"
    case documentReference              = "DocumentReference"
    case encounter                      = "Encounter"
    case endpoint                       = "Endpoint"
    case enrollmentRequest              = "EnrollmentRequest"
    case enrollmentResponse             = "EnrollmentResponse"
    case episodeOfCare                  = "EpisodeOfCare"
    case eventDefinition                = "EventDefinition"
    case evidence                       = "Evidence"
    case evidenceReport                 = "EvidenceReport"
    case evidenceVariable               = "EvidenceVariable"
    case exampleScenario                = "ExampleScenario"
    case explanationOfBenefit           = "ExplanationOfBenefit"
    case familyMemberHistory            = "FamilyMemberHistory"
    case flag                           = "Flag"
    case goal                           = "Goal"
    case graphDefinition                = "GraphDefinition"
    case group                          = "Group"
    case guidanceResponse               = "GuidanceResponse"
    case healthcareService              = "HealthcareService"
    case imagingStudy                   = "ImagingStudy"
    case immunization                   = "Immunization"
    case immunizationEvaluation         = "ImmunizationEvaluation"
    case immunizationRecommendation     = "ImmunizationRecommendation"
    case implementationGuide            = "ImplementationGuide"
    case ingredient                     = "Ingredient"
    case insurancePlan                  = "InsurancePlan"
    case invoice                        = "Invoice"
    case library                        = "Library"
    case linkage                        = "Linkage"
    case list                           = "List"
    case location                       = "Location"
    case manufacturedItemDefinition     = "ManufacturedItemDefinition"
    case measure                        = "Measure"
    case measureReport                  = "MeasureReport"
    case media                          = "Media"
    case medication                     = "Medication"
    case medicationAdministration       = "MedicationAdministration"
    case medicationDispense             = "MedicationDispense"
    case medicationKnowledge            = "MedicationKnowledge"
    case medicationRequest              = "MedicationRequest"
    case medicationStatement            = "MedicationStatement"
    case medicinalProductDefinition     = "MedicinalProductDefinition"
    case messageDefinition              = "MessageDefinition"
    case messageHeader                  = "MessageHeader"
    case molecularSequence              = "MolecularSequence"
    case namingSystem                   = "NamingSystem"
    case nutritionOrder                 = "NutritionOrder"
    case nutritionProduct               = "NutritionProduct"
    case observation                    = "Observation"
    case observationDefinition          = "ObservationDefinition"
    case operationDefinition            = "OperationDefinition"
    case operationOutcome               = "OperationOutcome"
    case organization                   = "Organization"
    case organizationAffiliation        = "OrganizationAffiliation"
    case packagedProductDefinition      = "PackagedProductDefinition"
    case patient                        = "Patient"
    case paymentNotice                  = "PaymentNotice"
    case paymentReconciliation          = "PaymentReconciliation"
    case person                         = "Person"
    case planDefinition                 = "PlanDefinition"
    case practitioner                   = "Practitioner"
    case practitionerRole               = "PractitionerRole"
    case procedure                      = "Procedure"
    case provenance                     = "Provenance"
    case questionnaire                  = "Questionnaire"
    case questionnaireResponse          = "QuestionnaireResponse"
    case regulatedAuthorization         = "RegulatedAuthorization"
    case relatedPerson                  = "RelatedPerson"
    case requestGroup                   = "RequestGroup"
    case researchDefinition             = "ResearchDefinition"
    case researchElementDefinition      = "ResearchElementDefinition"
    case researchStudy                  = "ResearchStudy"
    case researchSubject                = "ResearchSubject"
    case riskAssessment                 = "RiskAssessment"
    case schedule                       = "Schedule"
    case searchParameter                = "SearchParameter"
    case serviceRequest                 = "ServiceRequest"
    case slot                           = "Slot"
    case specimen                       = "Specimen"
    case specimenDefinition             = "SpecimenDefinition"
    case structureDefinition            = "StructureDefinition"
    case structureMap                   = "StructureMap"
    case subscription                   = "Subscription"
    case subscriptionStatus             = "SubscriptionStatus"
    case subscriptionTopic              = "SubscriptionTopic"
    case substance                      = "Substance"
    case substanceDefinition            = "SubstanceDefinition"
    case supplyDelivery                 = "SupplyDelivery"
    case supplyRequest                  = "SupplyRequest"
    case task                           = "Task"
    case terminologyCapabilities        = "TerminologyCapabilities"
    case testReport                     = "TestReport"
    case testScript                     = "TestScript"
    case valueSet                       = "ValueSet"
    case verificationResult             = "VerificationResult"
    case visionPrescription             = "VisionPrescription"

    public static let Version = "4.3.0"

    func profileName() -> String {
        self.rawValue.lowercased() + ".profile.json"
    }
}
